// Generates a French Horn mute adapted from US Patent 1,425,318 (E. A. Couturier, 1922),
// originally designed for cornet/trumpet.
// STATUS: ALPHA -- new design, unfitted; dimensions are a first-pass estimate.
// ©2026 by Don Ankney
// This code is licensed under GNU General Public License v2.0. To view a copy of this license, visit https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
// Models generated by this code are licensed under CC BY-SA 4.0. To view a copy of this license, visit https://creativecommons.org/licenses/by-sa/4.0/
//
// Patent geometry (reference numbers match the original drawings):
//   13 - bell-shaped body, conforms to the horn bell's taper but stays smaller so it
//        floats clear of the bell wall (mounting/annulus 12 not yet implemented --
//        the previous 3-cork stand-in was removed as incorrect)
//   14 - hemispherical closure capping body 13's larger (outer) end, convex side out
//   15 - re-entrant sound delivery slit through the center of 14: a lens (orange-
//        segment) shape cut through the dome, wide at the pole (the outer/
//        delivery end) and narrowing to a hairline at z=0, the center of the
//        sphere Closure14 is a hemisphere of (Body13's plane of maximum diameter
//        -- Claims 1, 4 & 5). Only its width tapers; its length (CutLength) is
//        held constant and set well beyond the sphere's own full diameter line
//        -- see the CutLength comment for why it can't just barely clear that
//        diameter -- so the cut always exceeds the dome's local diameter and
//        reaches all the way to z=0. Its axial span equals the closure's radius
//        (Claim 2). Cut as a subtraction from Closure14, not a separate added
//        tube
//   12 - resilient annulus gripping body 13's smaller (inner) end, wedged into the
//        bell bore. Not yet implemented -- TODO, see 13 above
//   16 - the small, inner end of body 13
//
// z = 0 is the bell-mouth (outer) side, where the dome sits; z = BellHeight is the
// deep (inner) side, where end 16 and the (future) mounting annulus sit. This
// matches Rittich.scad's own convention.
// The bell envelope (BellBaseD/BellOpenD/BellHeight) is carried over from
// Rittich.scad unchanged (same fitted profile) -- that file is not altered, so
// the relevant geometry is duplicated here instead.
//
// Recommended print orientation: end 16 (the small tip) down on the bed, dome pole
// up. Body13 then widens going up at a gentle ~11.6 deg from vertical (safe), and
// the dome narrows back to a point above that (always safe, since radius decreases
// going up). The reverse orientation -- dome pole down -- puts a near-horizontal,
// unsupported overhang right at the base (the sphere's surface starts at ~87 deg
// from vertical at the pole and only eases below 45 deg about 20mm up).

// ---- Dimensions -----------------------------------------------------------------
// Bell reference envelope (Rittich.scad's fitted French horn bell profile)
BellBaseD  = 127.5;    // bell ID at the shallow/outer end (z = 0)
BellOpenD  = 27.5;     // bell ID at the deep/inner end (z = BellHeight)
BellHeight = 244.2;

// Body 13: shrunk inside the bell envelope so it floats clear of the bell wall.
RadialClearance = 6;   // gap, in radius, between Body13's outer wall and the bell
WallThickness    = 1;  // printed shell wall (matches Rittich)

BodyBaseD = BellBaseD - 2 * RadialClearance;   // 115.5
BodyOpenD = BellOpenD - 2 * RadialClearance;   // 15.5

// Closure 14 (radius also used as Tube 15's length, per Claim 2)
DomeRadius        = BodyBaseD / 2 + WallThickness;   // 58.75, flush with Body13 at z=0
DomeWallThickness = WallThickness;

// Tube 15: a tapering slot cut through Closure14 -- see the header note. "Length"
// runs east-west and is held constant (see CutLength below) rather than tapering,
// so it always exceeds the dome's local diameter and the cut reaches all the way
// to z=0; only "width" (the short axis) tapers.
TubeOuterWidth = 16;    // width at the pole (delivery end)
TubeInnerWidth = 0.5;   // width at z=0 -- tapers to (near) a true point

// CutLength must clear the sphere's own full diameter (2*DomeRadius) by a wide
// margin, not just a few mm. The lens shape (orangeSlice2D) itself tapers to a
// point at its own tips; if CutLength is only slightly more than the dome's
// diameter, the dome's equator (its widest ring, radius DomeRadius) sits very
// close to the lens's own tip -- e.g. at CutLength = 2*DomeRadius+10, that ring
// sits at 92% of the way out to the tip, where the lens's *own* built-in taper
// has already collapsed its width to ~19% of nominal. That stacks with the
// intentional pole-to-equator width taper below and cancels the cut almost
// entirely right where it needs to still be open. At 400mm the ring sits at
// only ~29% of the way to the tip (~93% of nominal width retained), so the cut
// width near z=0 is governed by TubeInnerWidth as intended, not swallowed by
// the lens's own geometry.
CutLength = 400;

CircleResolution = 360;
SphereResolution = 90;

// ---- Body 13: the resonating bell-shaped shell -----------------------------------
// Open at both ends: z=0 joins Closure14 (same radius, see DomeRadius); z=BellHeight
// (end 16) is open to the bell's interior.
module Body13() {
    difference() {
        cylinder($fn = CircleResolution, h = BellHeight, r1 = BodyBaseD / 2 + WallThickness, r2 = BodyOpenD / 2 + WallThickness);
        translate([0, 0, -0.1])
            cylinder($fn = CircleResolution, h = BellHeight + 0.2, r1 = BodyBaseD / 2, r2 = BodyOpenD / 2);
    }
}

// ---- Closure 14: hemispherical dome capping Body13's larger (outer) end ---------
// Convex side faces outward (negative z), away from the instrument. Solid shell;
// Tube15 is cut into it separately (see RigidBody).
module Closure14() {
    intersection() {
        difference() {
            sphere(r = DomeRadius, $fn = SphereResolution);
            sphere(r = DomeRadius - DomeWallThickness, $fn = SphereResolution);
        }
        translate([-(DomeRadius + 1), -(DomeRadius + 1), -(DomeRadius + 1)])
            cube([2 * (DomeRadius + 1), 2 * (DomeRadius + 1), DomeRadius + 1]);
    }
}

// ---- Tube 15: tapering slot cut through Closure14 --------------------------------
// A solid lens (vesica piscis) shape, wide at the pole and narrow at z=0, used as a
// cutter and subtracted from Closure14 in RigidBody -- not a separate added part.
// Length runs east-west; unlike a constant-angle wedge, this taper is independent
// of the sphere's own curvature, so it can be widest right at the pole. Curved,
// pointed ends (an actual orange-segment profile) rather than a flat-sided,
// rounded-cap stadium.
//
// Built by stretching a fixed, well-proportioned reference lens (two unit circles,
// good tessellation at any $fn) to the target length/width via resize(), rather
// than solving for a supporting circle radius R directly from length and width.
// That direct-solve approach (R = (w^2+l^2)/4w) blows up for the very elongated
// slits this needs (length up to ~127mm, width down to ~0.5mm): at the narrow end
// R comes out over 8 METERS, and at CircleResolution=360 each facet on a circle
// that size is >100mm long -- far coarser than the whole feature -- so the
// intersection degenerated into a corrupted blob instead of a clean sliver.
// resize() sidesteps this: the reference circles stay small (r=1) and smoothly
// tessellated regardless of the final aspect ratio.
module orangeSlice2D(length, width) {
    resize([length, width])
        intersection() {
            translate([0, -0.6]) circle(r = 1, $fn = CircleResolution);
            translate([0, 0.6]) circle(r = 1, $fn = CircleResolution);
        }
}

module Tube15() {
    overshoot = 2;   // past z=0, so the cut fully opens into Body13's cavity instead
                      // of leaving a coincident-face membrane at z=0
    union() {
        translate([0, 0, -DomeRadius])
            linear_extrude(height = DomeRadius, scale = [1, TubeInnerWidth / TubeOuterWidth])
                orangeSlice2D(CutLength, TubeOuterWidth);
        translate([0, 0, -0.1])
            linear_extrude(height = overshoot + 0.1)
                orangeSlice2D(CutLength, TubeInnerWidth);
    }
}

// ---- Assembly ---------------------------------------------------------------------
// TODO: mounting annulus 12 (was 3 TPU corks; removed as incorrect, to be redone)
module RigidBody() {
    difference() {
        union() {
            Body13();
            Closure14();
        }
        Tube15();
    }
}

RigidBody();
