// Generates a Non-transposing Stop Mute
// ©2026 by Don Ankney
// This code is licensed under GNU General Public License v2.0. To view a copy of this license, visit https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
// Models generated by this code are licensed underis licensed under CC BY-SA 4.0. To view a copy of this license, visit https://creativecommons.org/licenses/by-sa/4.0/


// Dependencies
//  -- https://github.com/BelfrySCAD/BOSL2

include <BOSL2/std.scad>
include <BOSL2/threading.scad>


// Default Dimensions (also declares variable in global scope)
    VariantName = "Default";
    LowerCirc = 325;
    UpperCirc = 310;
    BaseHeight = 65;
    TipExtD = 40;
    TipIntD = 30;  
    TubeRadius = 20;
    TubeHeight = 150;
    TotalHeight = 195;
    tubeMountHeight = 30;
    wallThickness = 2;
    circleRes = 360;

// Base Section
module baseSection (lowerCirc, upperCirc, baseHeight, wallThickness) { 
    lowerR = lowerCirc / PI / 2;
    upperR = upperCirc / PI / 2;
    difference() {
        cylinder($fn = circleRes, baseHeight, lowerR + wallThickness, upperR + wallThickness, center=false);
        cylinder($fn = circleRes, baseHeight, r1=lowerR, r2 = upperR, center = false);
    }
}


// Tube Mount
module tubeMount(innerRadius, wallThickness, mountHeight = 30) {
   difference(){
       union(){

              translate([0, 0, 5])
                cylinder($fn = circleRes, h = mountHeight - 5, r = innerRadius + wallThickness, center = false);

            rotate_extrude(convexity = 10, $fn = circleRes)
                translate([0.1,0,0])
                    polygon(points = [[innerRadius + 5 + wallThickness ,0], [0,innerRadius], [innerRadius + 5, innerRadius ]]);
        }
          
       //cylinder(h = mountHeight, r = innerRadius, center = false);
       trapezoidal_threaded_rod(d = innerRadius * 2, l = mountHeight * 3, pitch = 3, internal = true);
   }

}

// Top Section with Tube Mount
module topSection (baseC, topD, topHeight, wallThickness) {
    baseR = baseC / PI / 2;
    topR = topD / 2;

    
    difference() {
        cylinder ($fn = circleRes, h = topHeight, r1 = baseR + wallThickness, r2 = topR + wallThickness);
        cylinder ($fn = circleRes, h = topHeight, r1 = baseR, r2 = topR);
    }
    translate([0, 0, topHeight - tubeMountHeight])
        tubeMount(TubeRadius, wallThickness, tubeMountHeight);     
}


// Text On Bottom
module watermark (RADIUS, RADIUS2, ARC_ANGLE, stext) {
    
    chars = len( stext );
   
    difference(){
        cylinder($fn=circleRes, r1=RADIUS, r2= RADIUS2 + 2, h=10,center=true);

        for(i=[0:1:chars]){
            rotate([0,0,i*ARC_ANGLE/chars]){
                translate( [RADIUS*.95,0,0])
            rotate([90,0,90])
            linear_extrude(7)
                text(stext[i],size=6, valign="center",halign="center");
            }
        }
    }
    //Cup and Pipe
    translate([0,0,-5])
        cylinder($fn=circleRes, r1=RADIUS2-2, r2= 5, h=28,center=false);
        translate([0,0,23])
            cylinder($fn=360, h=34, r1=6, r2=4, center=false);
}


  //      union(){
    //        translate([0,0,-5])
      //          cylinder($fn=circleRes, r1=RADIUS2-4, r2= 3, h=28,center=false);
        //    translate([0,0,23])
          //      cylinder($fn=360, h=34, r1=3, r2=3, center=false);
     //   }

// Mute Body Assembly
module mute(){
    difference() {
        union() {
            translate([0, 0,  BaseHeight])
                topSection(UpperCirc, TipExtD, TotalHeight - BaseHeight, wallThickness);
            
            baseSection(LowerCirc, UpperCirc, BaseHeight, wallThickness);
            
            cylinder($fn = circleRes, h = 10, r = LowerCirc / PI / 2);
            
            translate([0,0,-5])
                watermark(RADIUS = UpperCirc / PI / 2, RADIUS2 = LowerCirc / PI / 2, ARC_ANGLE = 160, stext = [ "h","o","r","n","-","m", "u","t","e","s",".","c", "o", "m" ]);
        }
        //Cup and Pipe
        union(){
            translate([0,0,-10])
            cylinder($fn=circleRes, r1=lowerCirc / PI / 2 - 4, r2= 5, h=28,center=false);
            translate([0,0,23])
                cylinder($fn=360, h=34, r1=3, r2=3, center=false);
        }
    }
}
mute();
//watermark(RADIUS = UpperCirc / PI / 2, RADIUS2 = LowerCirc / PI / 2, ARC_ANGLE = 160, stext = [ "h","o","r","n","-","m", "u","t","e","s",".","c", "o", "m" ]);