// Generates a Practice Mute (cloned from the DePolis-style Straight Mute)
// STATUS: BETA -- in active testing; dimensions and features are not finalized.
// ©2025 by Don Ankney
// This code is licensed under GNU General Public License v2.0. To view a copy of this license, visit https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
// Models generated by this code are licensed underis licensed under CC BY-SA 4.0. To view a copy of this license, visit https://creativecommons.org/licenses/by-sa/4.0/


// Dependencies
//  -- https://github.com/BelfrySCAD/BOSL2

include <BOSL2/std.scad>
include <BOSL2/threading.scad>

// Default Dimensions (also declares variable in global scope)
    VariantName = "Default";
    LowerCirc = 325;
    UpperCirc = 310;
    BaseHeight = 65;
    TipExtD = 40;
    TipIntD = 30;
    TubeRadius = 20;
    TubeHeight = 150;
    TotalHeight = 195;
    tubeMountHeight = 30;
    wallThickness = 2;
    threadClearance = 1.0; // diametral gap between tube thread and mount opening; printed trapezoidal threads need ~0.5mm radial to assemble
    circleRes = 360;

// Base Section
module baseSection (lowerCirc, upperCirc, baseHeight, wallThickness) {
    lowerR = lowerCirc / PI / 2;
    upperR = upperCirc / PI / 2;
    difference() {
        cylinder($fn = circleRes, baseHeight, lowerR + wallThickness, upperR + wallThickness, center=false);
        cylinder($fn = circleRes, baseHeight, r1=lowerR, r2 = upperR, center = false);
    }
}


// Tube Mount
module tubeMount(innerRadius, wallThickness, mountHeight = 30) {
   difference(){
       union(){

              translate([0, 0, 5])
                cylinder($fn = circleRes, h = mountHeight - 5, r = innerRadius + wallThickness, center = false);

            rotate_extrude(convexity = 10, $fn = circleRes)
                translate([0.1,0,0])
                    polygon(points = [[innerRadius + 5 + wallThickness ,0], [0,innerRadius], [innerRadius + 5, innerRadius ]]);
        }

       //cylinder(h = mountHeight, r = innerRadius, center = false);
       trapezoidal_threaded_rod(d = innerRadius * 2, l = mountHeight * 3, pitch = 3, internal = true);
   }

}

// Top Section with Tube Mount
module topSection (baseC, topD, topHeight, wallThickness, tubeRadius, tubeMountHeight) {
    baseR = baseC / PI / 2;
    topR = topD / 2;

    // Minor (crest) radius of the mount's internal thread; pitch=3 -> depth=pitch/2.
    threadMinorR = tubeRadius - 3/2;
    mountOuterR = tubeRadius + wallThickness;
    // Lead-in chamfer height at the very top of the bore. Kept small enough that the bevel
    // stays inside mountOuterR and leaves a solid rim.
    bevelHeight = 2;

    // Height at which the wall's outer cone has narrowed to the mount's outer radius. Below
    // this the wall is wider than the mount; above it the mount stands proud. The mount's own
    // flare used to bulge past the wall here, leaving a raised ring with a flat, downward-facing
    // underside (an unsupported arch that prints badly). Clip the mount flush to the wall so the
    // outer surface stays a continuous cone, then a plain vertical collar where the wall is
    // narrower than the mount -- no ledge, no overhang.
    wallOuterBase = baseR + wallThickness;
    wallOuterTop = topR + wallThickness;
    crossH = (mountOuterR - wallOuterBase) / (wallOuterTop - wallOuterBase) * topHeight;

    difference() {
        intersection() {
        union() {
            // Mute wall (hollow cone). The wall tapers narrower than the mount near the tip;
            // without intervention it interpenetrates the threads, which both pinched the bore
            // and left non-manifold grazing edges. Carve a clean cylindrical pocket (just inside
            // the mount's outer radius so they still overlap) to keep the wall off the threads.
            difference() {
                cylinder ($fn = circleRes, h = topHeight, r1 = baseR + wallThickness, r2 = topR + wallThickness);
                cylinder ($fn = circleRes, h = topHeight, r1 = baseR, r2 = topR);
                translate([0, 0, topHeight - tubeMountHeight - 0.01])
                    cylinder ($fn = circleRes, h = tubeMountHeight + 1, r = mountOuterR - 0.5);
            }
            translate([0, 0, topHeight - tubeMountHeight])
                tubeMount(tubeRadius, wallThickness, tubeMountHeight);
        }
        // Outer envelope: the wall cone up to where it meets the mount, then a vertical collar.
        // Anything the mount flares beyond this (the old ring) gets shaved off flush. The small
        // margins keep the wall/collar surfaces themselves untouched (no coincident-face slivers).
        union() {
            cylinder ($fn = circleRes, h = topHeight,
                      r1 = wallOuterBase + 0.01, r2 = wallOuterTop + 0.01);
            translate([0, 0, crossH])
                cylinder ($fn = circleRes, h = topHeight - crossH + 1, r = mountOuterR + 0.01);
        }
        }
        // Lead-in bevel: widen the bore from the top of the threading out to the very top
        // so the tube starts easily. Overshoots past the top face for a clean cut.
        translate([0, 0, topHeight - bevelHeight])
            cylinder ($fn = circleRes, h = bevelHeight + 1,
                      r1 = threadMinorR + 0.2, r2 = threadMinorR + 0.2 + bevelHeight + 1);
    }
}

// Tube
module tuningTube(tubeRadius, tubeLength, wallThickness) {
    extDiameter = tubeRadius * 2 + 4 * wallThickness;
    intRadius = tubeRadius;

    difference() {
        union(){
            cylinder(h=5, r1=tubeRadius, r2=tubeRadius + 6); // Flared end to make it easier to insert into the mute
            translate([0, 0, tubeLength - (tubeLength / 1.5)])
                trapezoidal_threaded_rod(d=extDiameter, h=tubeLength/2, pitch=3);
            cylinder(h=tubeLength, d=extDiameter-3);
        }
        cylinder(h=tubeLength, r1=intRadius, r2=intRadius, center=false);
    }
}


// Text On Bottom
module watermark (RADIUS, RADIUS2, ARC_ANGLE, stext) {

    chars = len( stext );

    difference(){
        cylinder($fn=circleRes, r1=RADIUS, r2= RADIUS2 + 2, h=10,center=true);

        for(i=[0:1:chars]){
          rotate([0,0,i*ARC_ANGLE/chars]){
            translate( [RADIUS*.95,0,0])
              rotate([90,0,90])
                linear_extrude(7)
                  text(stext[i],size=6, valign="center",halign="center");
            }
        }
    }
}

// Pressure-relief vents: a ring of small holes drilled diagonally from the hollow
// interior out through the bottom edge, to bleed off internal air pressure and make
// this a practice mute.
module pressureReliefHoles(lowerCirc, wallThickness, count = 12, holeD = 2, tilt = 45) {
    baseOuterR = lowerCirc / PI / 2 + wallThickness;   // outer radius at the bottom rim
    for (i = [0 : count - 1]) {
        rotate([0, 0, i * 360 / count])
            translate([baseOuterR, 0, 0])              // exit right at the bottom outer edge (rim corner)
                rotate([0, -tilt, 0])                  // lean the drill inward and upward
                    translate([0, 0, -6])              // back the bit out so it starts outside the surface
                        cylinder($fn = 24, h = 30, d = holeD);
    }
}

// A second ring of vents dropped straight down from the interior cavity, through the
// large base end cap, to the very bottom face. Offset halfway between the diagonal
// vents above.
module verticalVents(lowerCirc, count = 12, holeD = 2) {
    ventR = lowerCirc / PI / 2 - 6;                    // inboard of the bottom rim so it stays within the end cap and exits the flat bottom
    for (i = [0 : count - 1]) {
        rotate([0, 0, i * 360 / count + 180 / count])  // bisect the gaps between the diagonal vents
            translate([ventR, 0, -12])                  // start below the bottom face
                cylinder($fn = 24, h = 30, d = holeD);  // straight up through the end cap into the cavity
    }
}

// Mute Body Assembly
module mute(lowerCirc, upperCirc, baseHeight, tipExtD, totalHeight, wallThickness, tubeRadius, tubeMountHeight){
    difference() {
        union() {
            translate([0, 0,  baseHeight])
                topSection(upperCirc, tipExtD, totalHeight - baseHeight, wallThickness, tubeRadius, tubeMountHeight);

            baseSection(lowerCirc, upperCirc, baseHeight, wallThickness);

            cylinder($fn = circleRes, h = 10, r = lowerCirc / PI / 2);

            translate([0,0,-5])
                watermark(RADIUS = upperCirc / PI / 2, RADIUS2 = lowerCirc / PI / 2, ARC_ANGLE = 160, stext = [ "h","o","r","n","-","m", "u","t","e","s",".","c", "o", "m" ]);
        }

        pressureReliefHoles(lowerCirc, wallThickness);
        verticalVents(lowerCirc);
    }
}


// There are three variations
// To choose which variation of the DePolis Mute to generate, set this variable
muteVariation = "3";

//JR Variant
if (muteVariation == "2") {
    // Dimensions
    echo("ONE");
    VariantName = "JR Variant";
    LowerCirc = 290;
    UpperCirc = 290;
    BaseHeight = 90;
    TipExtD = 45;
    TipIntD = 40;
    TubeRadius = 22.5;
    TubeHeight = 150;
    TotalHeight = 175;
    tubeMountHeight = 30;
    wallThickness = 2;
    circleRes = 360;
    // Render Mute
    mute(LowerCirc, UpperCirc, BaseHeight, TipExtD, TotalHeight, wallThickness, TubeRadius, tubeMountHeight);
    translate([LowerCirc / PI, LowerCirc / PI, - 10])
        tuningTube(TubeRadius - 2 * wallThickness - threadClearance / 2, TubeHeight, wallThickness);
} else

// DW Variant
if (muteVariation == "2") {
    VariantName = "DW Variant";
    echo("TWO");
    echo(VariantName);
    LowerCirc = 325;
    UpperCirc = 325;
    BaseHeight = 65;
    TipExtD = 45;
    TipIntD = 35;
    TubeRadius = 22.5;
    TubeHeight = 130;
    TotalHeight = 175;
    tubeMountHeight = 30;
    wallThickness = 2;
    circleRes = 360;

    // Render Mute
    mute(LowerCirc, UpperCirc, BaseHeight, TipExtD, TotalHeight, wallThickness, TubeRadius, tubeMountHeight);
    translate([LowerCirc / PI, LowerCirc / PI, - 10])
        tuningTube(TubeRadius - 2 * wallThickness - threadClearance / 2, TubeHeight, wallThickness);
} else

// HB Variant
if (muteVariation == "3") {
   VariantName = "HB Variant";
    LowerCirc = 325;
    UpperCirc = 310;
    BaseHeight = 65;
    TipExtD = 40;
    TipIntD = 30;
    TubeRadius = 22.5;
    TubeHeight = 150;
    TotalHeight = 195;
    tubeMountHeight = 30;
    wallThickness = 2;
    circleRes = 360;

    // Render Mute
    mute(LowerCirc, UpperCirc, BaseHeight, TipExtD, TotalHeight, wallThickness, TubeRadius, tubeMountHeight);
    translate([LowerCirc / PI, LowerCirc / PI, - 10])
        tuningTube(TubeRadius - 2 * wallThickness - threadClearance / 2, TubeHeight, wallThickness);


}
